name: Cleanup Expired Public Locations

on:
  # Run every hour
  schedule:
    - cron: '0 * * * *'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger cleanup endpoint
        run: |
          RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            "${{ secrets.APP_URL }}/api/cleanup/expired-locations")
          
          HTTP_CODE=$(echo "$RESPONSE" | grep "HTTP_CODE:" | cut -d':' -f2)
          BODY=$(echo "$RESPONSE" | sed '/HTTP_CODE:/d')
          
          echo "Response: $BODY"
          echo "HTTP Code: $HTTP_CODE"
          
          if [ "$HTTP_CODE" -ne 200 ]; then
            echo "❌ Cleanup failed with HTTP code $HTTP_CODE"
            exit 1
          fi
          
          echo "✅ Cleanup completed successfully"

      - name: Notify on failure
        if: failure()
        run: |
          echo "⚠️ Cleanup job failed! Check the logs above."
          # You can add additional notification logic here (email, Slack, etc.)
